server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yassinebouharb/config-server
          default-label: master
          clone-on-start: true
          username: yassine.bouharb@esprit.tn
          password: sagemcom66