server:
  port: 8008

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yassinebouharb/config-server
          default-label: main
          clone-on-start: true