spring:
  datasource:
    url: jdbc:mysql://localhost:3306/produitsdb
    username: "root"
    password:  ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
